from pathlib import Path

path = Path('pages/Dashboard.jsx')
text = path.read_text()
old = "            <div className=\"bg-[#101b30] border border-slate-800/70 rounded-2xl p-4 shadow-inner shadow-slate-900/40\">\r\n              <p className=\"text-xs uppercase tracking-widest text-slate-500\">Blocked IPs</p>\r\n              <p className=\"text-3xl font-semibold text-rose-300 mt-2\">{blocklistFetching && !blockedIpsCount ? '--' : blockedIpsCount}</p>\r\n              <p className=\"text-[11px] text-slate-500 mt-1\">Blocked devices: {metrics.blockedDevices}</p>\r\n            </div>\r\n"
new = "            <div className=\"bg-[#101b30] border border-slate-800/70 rounded-2xl p-4 shadow-inner shadow-slate-900/40\">\r\n              <p className=\"text-xs uppercase tracking-widest text-slate-500\">Blocked IPs</p>\r\n              <p className=\"text-3xl font-semibold text-rose-300 mt-2\">{blocklistFetching && !blockedIpsCount ? '--' : blockedIpsCount}</p>\r\n              <p className=\"text-[11px] text-slate-500 mt-1\">Blocked devices: {metrics.blockedDevices}</p>\r\n              <div className=\"mt-3 border-t border-slate-800/60 pt-3\">\r\n                <p className=\"text-[11px] uppercase tracking-widest text-slate-500\">Recent entries</p>\r\n                <ul className=\"mt-2 space-y-1 text-xs\">\r\n                  {blockedIpsPreview.length ? (\r\n                    blockedIpsPreview.map((entry, index) => {\r\n                      const ipValue = typeof entry === 'string' ? entry : entry?.ip;\r\n                      const createdAtRaw = entry && typeof entry === 'object' ? entry?.created_at : null;\r\n                      const createdAtLabel = createdAtRaw ? new Date(createdAtRaw).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : null;\r\n                      return (\r\n                        <li key={ipValue || index} className=\"flex items-center justify-between gap-2 text-slate-300\">\r\n                          <span className=\"font-mono\">{ipValue || 'Unknown'}</span>\r\n                          {createdAtLabel && (<span className=\"text-[10px] text-slate-500\">{createdAtLabel}</span>)}\r\n                        </li>\r\n                      );\r\n                    })\r\n                  ) : (\r\n                    <li className=\"text-[11px] text-slate-500\">No IPs currently blocked.</li>\r\n                  )}\r\n                </ul>\r\n                {remainingBlockedIps > 0 && (\r\n                  <p className=\"text-[10px] text-slate-500 mt-1\">+ {remainingBlockedIps} more in blocklist</p>\r\n                )}\r\n              </div>\r\n            </div>\r\n"
if old not in text:
    raise SystemExit('old block not found')
text = text.replace(old, new, 1)
path.write_text(text)
